### ISSUE TITLE
License

### ISSUE THREAD

**Issue by btopro** [pushkar8723/paper-dropdown#1]
Great element. I'd consider making this Apache 2 / MIT or something with better Copy left / modification rights. GPLv3 is very hard to get people to contribute to since it effectively requires either that it's the highest licensed item in a project or that everything made off of it is also GPLv3.

**Comment by pushkar8723** [comment]
I am no expert at this, I licensed it under GPL-3 to encourage open source contributions as suggested [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project). 

If more people from community feel the same way, I will definitely switch to Apache 2.

**Comment by btopro** [comment]
It says that if you don't know what to use, MIT is probably the way to go. GPLv3 is more of a purist license great for top level applications but less so for nuts and bolts sorta stuff like our elements

**Comment by pushkar8723** [comment]
Makes sense. Will change license to MIT in next release.
