### ISSUE TITLE
Doesn't work with multi and dom-repeat

### ISSUE THREAD

**Issue by Boscop** [pushkar8723/paper-dropdown#2]
This doesn't work:
```html
              <paper-dropdown label="Route" value="{{route_value}}" searchable multi>
                <template is="dom-repeat" items="[[places_res]]" as="place">
                  <paper-item value="[[place.id]]">[[place.name]]</paper-item>
                </template>
              </paper-dropdown>
```
The dropdown opens but I can't select anything, neither by clicking in the checkbox nor on the item itself. It only works without `multi` but I need multiselection.. (Removing `searchable` doesn't help.)
Any idea why it's not working?

Btw, why does the selected index start at 1?

**Comment by pushkar8723** [comment]
Since value is not a property of ```paper-item``` you have to use $= for binding.
Refer [https://www.polymer-project.org/1.0/docs/devguide/data-binding](https://www.polymer-project.org/1.0/docs/devguide/data-binding) for more information.
So your code should be:
```html
<paper-dropdown label="Route" value="{{route_value}}" searchable multi>
     <template is="dom-repeat" items="[[places_res]]" as="place">
         <paper-item value$="[[place.id]]">[[place.name]]</paper-item>
    </template>
 </paper-dropdown>
```
Selected index start at 1 as 0th index is occupied by the search box.
Removing searchable property will make it start from 0.
Will fix this in future version.

**Comment by pushkar8723** [comment]
Closing this issue.
Opened #3 for selected index.

**Comment by IchordeDionysos** [comment]
Would be great to add an example for this case as I tried to debug this for hours...

Or just to change this function:

```
_getItemValue: function (item) {
  if (item) {
    if (item.getAttribute('value'))
      return item.getAttribute('value');
    else
      return item.textContent.trim();
  }
}
```

to this:

```
_getItemValue: function (item) {
  if (item) {
    if (item.getAttribute('value'))
      return item.getAttribute('value');
    else if (item.value)
      return item.value;
    else
      return item.textContent.trim();
  }
}
```

**Comment by pushkar8723** [comment]
Last example in [README file](https://github.com/pushkar8723/paper-dropdown/blob/master/README.md) addresses this issue.

You can see it in action @ [https://www.webcomponents.org/element/pushkar8723/paper-dropdown](https://www.webcomponents.org/element/pushkar8723/paper-dropdown)
