### ISSUE TITLE
Please make API more similar to paper-dropdown-menu

### ISSUE THREAD

**Issue by Boscop** [pushkar8723/paper-dropdown#4]
Can you please make this element's api the same as `paper-dropdown-menu`?
So that it has a `selected` attribute and `attr-for-selected` so that it can be used the same, like this:
```html
    <paper-dropdown-menu label="name">
      <paper-listbox class="dropdown-content" selected="{{sel}}" attr-for-selected="value">
        <template is="dom-repeat" items="[[res]]" as="item">
          <paper-item value="[[item.id]]">[[item.unique_id]]</paper-item>
        </template>
      </paper-listbox>
    </paper-dropdown-menu>

    <paper-dropdown label="name" selected="{{sel}}" attr-for-selected="value" searchable>
      <template is="dom-repeat" items="[[res]]" as="item">
          <paper-item value="[[item.id]]">[[item.unique_id]]</paper-item>
      </template>
    </paper-dropdown>
```

Currently, that's not possible, when I write this:
```html
    <paper-dropdown label="name" value="{{sel}}" searchable>
```
I don't get the actual id but the displayed value, which is very cumbersome to work with..

Or is there a similar way that I'm not seeing to get the actual value that I want (item.id) in a declarative way (without js post-processing)?

**Comment by pushkar8723** [comment]
Paper-dropdown was made for this scenario especially, i.e. you can show a value in dropdown and get its id/key in `value` property of paper-dropdown and not index like you would get in your paper-dropdown-menu snippet. Eleminating the need of js post-processing.
Also, you made the same mistake of confusing attribute with property. Please go through the link I provided in #2.
I would recommend you to go through demos available in paper-dropdown which depicts many common scenarios including the one you mention (without template-repeat).

So for your use-case, you can use paper-dropdown as given in snippet below (notice `$` after value in `paper-item`):
```html
    <paper-dropdown label="name" value="{{sel}}" searchable>
      <template is="dom-repeat" items="[[res]]">
          <paper-item value$="[[item.id]]">[[item.unique_id]]</paper-item>
      </template>
    </paper-dropdown>
```

**Comment by Boscop** [comment]
Thanks!
Sorry, maybe this is a misunderstanding:
When I use that code, I don't get the `item.id` in `sel` but the displayed value.
How can I get the `item.id` in the `sel` variable (without js post-processing)?

**Comment by pushkar8723** [comment]
I have made a plunkr for this usecase. You can play with it [here](http://plnkr.co/edit/sRTiuTGXwDxTrJpZYVmf?p=preview).

*Note:* `vulcanized-output.html` is vulcanization of paper-dropdown and paper-item.

If you are still facing some issue, create a plunkr demonstrating the issue and give me the link.

P.S: Sorry for late reply.

**Comment by Boscop** [comment]
Ah thanks! I understand it now.. (Before, I thought it was only using the paper-items' content for its value.)
Btw, why does that plunkr also work when I remove the $ so it assigns the id as a `value` _property_?
Shouldn't it not work then?
Because it's fetching only the attribute here:
https://github.com/pushkar8723/paper-dropdown/blob/master/paper-dropdown.html#L434-L435
Or is there some magic going on that's correcting it somehow to assign to the `value` _attribute_?

Btw, in those two lines, the call doesn't have to be made twice, it can be cached like `var value = item.getAttribute('value'); if(value) return value; else ...` so be a little bit faster ;)

**Comment by pushkar8723** [comment]
I think you didn't re run the plunkr after making changes as when I try without $ it gives me the displayed value and not the key.

![plunkr](https://user-images.githubusercontent.com/2996493/33230383-90ae48e6-d208-11e7-9b8f-c583c9fd3b54.gif)
