### ISSUE TITLE
Doesn't work with Polymer 2.x

### ISSUE THREAD

**Issue by kylefarris** [pushkar8723/paper-dropdown#5]
This module seems like everything I need... just need it to work with Polymer 2. Would be awesome if you could find the time.

Thanks!

**Comment by pushkar8723** [comment]
I was waiting for 3.x to be released as they have already anounced it. But will port it to 2.x over weekend.

**Comment by kylefarris** [comment]
That makes sense. I don't think too much will be different in 3 other than how things are imported. Thanks a lot!

**Comment by pushkar8723** [comment]
Released version 2.0.0

**Comment by kylefarris** [comment]
Thanks!
