### ISSUE TITLE
Value send in form gets converted to string from object

### ISSUE THREAD

**Issue by HJK181** [pushkar8723/paper-dropdown#6]
Given the following code:
```
<iron-form...>
 <form...>
<paper-dropdown label="Tenants" name="tenants" value="{{selectedTenants}}" searchable="true" multi="true">
              <template is="dom-repeat" items="{{allTenants}}" as="tenant">
                <paper-item value$="[[tenant]]">[[tenant.name]].[[tenant.channel]]</paper-item>
              </template>
            </paper-dropdown>
</form>
</iron-form>
```

When Submitting the form the request body contains:
```0: "{name: "someName", channel: "someValue"}"```
Instead of 
```0: {name: "someName", channel: "someValue"}```

The reason being that is that ```item.getAttribute``` return a string representation of the object stored under value. Changing the code to ```item.value``` solves to problem for me. 

Could you provide some solution to stored objects in the value as well?

Another problem I'm facing is: How can I initially set the ```selectedTenants```? Something like this doesn't select the tenants:
```
 _activeItemChanged(item) {
           if (item) {
          this.selectedTenants = item.tenants;
           }
      }
```

**Comment by pushkar8723** [comment]
Instead of  ```this.selectedTenants = item.tenants``` try ```this.set('selectedTenants', item.tenants)```.
This should trigger the polymer's notification mechanism which in the former case is not being triggered.

**Comment by HJK181** [comment]
This doesn't help, as the value property is not reflected in your element. Only when the selectedItems of the paper-listbox change, the value property change. There is no other way around. Or do I miss something? 

Nvm. it should trigger _updateSelected ... but in my case nothing is selected.

**Comment by pushkar8723** [comment]
Can you create a plunkr or js bin for this? 
As in demo you can see there are two dropdown for multi-select option and setting value in one, updates the other one. So setting the value should be reflected in the element.

**Comment by HJK181** [comment]
Can u see this plunkr? http://plnkr.co/edit/NBK6qGRi58czF8GkkLtJ I'm not that familar with the tool.
The demo works fine. I think it is related to the other problem I described. I need to store object in the value, not strings like in the demos or plunkr.

**Comment by pushkar8723** [comment]
I would suggest you do something like http://plnkr.co/edit/N5SYC1v8qd363sJxQ57D?p=preview.
By using JSON.parse and JSON.stringify, you can achieve what you want.
This workaround is necessary because object comparision in javascript is done via reference and they will never match for such cases as described @ https://stackoverflow.com/questions/1068834/object-comparison-in-javascript and http://adripofjavascript.com/blog/drips/object-equality-in-javascript.html

**Comment by HJK181** [comment]
Thank you very much. I also found an other solution by using a hidden input ```<paper-input name="tenants" hidden value="[[selectedTenants]]" ></paper-input>```, storing the value as string ``` <paper-item value$=[[tenant.channel]]>[[tenant.name]].[[tenant.channel]]</paper-item>```

and applying the following map fn: ```this.set('selectedTenants', item.tenants.map(tenant => tenant.channel));```

But I will go for your solution as it is a log cleaner. Again, thank your for your help and time, great work.

**Comment by HJK181** [comment]
I was a bit to fast with my answer. The selection now works, but I'm still facing the problem of the wrong request body:

0: "{name: "someName", channel: "someValue"}"
Instead of
0: {name: "someName", channel: "someValue"}

That is because of   if (item.getAttribute('value')) will return a string.

**Comment by pushkar8723** [comment]
Use JSON.parse before submiting it to get back the object.
